### ISSUE TITLE
Importing the library using require 

### ISSUE THREAD

**Issue by Snorlite** [sindresorhus/file-metadata#3]
I'm using Node v16.6.0. I tried importing the library in this way:

`const fileMetadata = require("file-metadata");`

It returns `[ERR_REQUIRE_ESM]`. Is there no way to fix this?

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c#readable-named-exports
